import { Accessibility, Compass, HeartHandshake, Lightbulb, ShieldCheck, Target, UsersRound } from 'lucide-react';
import InstitutionalLayout, { ContentCard } from './InstitutionalLayout';

export default function AboutView({ onBack }: { onBack: () => void }) {
  const sections = [{id:'origen',label:'1. Nuestro origen'},{id:'mision',label:'2. Misión y visión'},{id:'principios',label:'3. Principios'},{id:'producto',label:'4. Qué construimos'},{id:'equipo',label:'5. Equipo'}];
  return <InstitutionalLayout eyebrow="Conoce el proyecto" title="Sobre TramIA" intro="Creamos una forma más clara y humana de entender, organizar y completar trámites en el Perú." mascot="/assets/mascot/tramia-bot-about.png" mascotAlt="TramIA presenta con orgullo el proyecto" sections={sections} onBack={onBack} badge="Información institucional temporal">
    <ContentCard id="origen" icon={Lightbulb} title="1. Nuestro origen"><p>TramIA nació como un prototipo de innovación de LegalIA, un venture de UTEC, para responder una pregunta sencilla: ¿por qué una persona debe conocer el nombre exacto de un trámite antes de recibir ayuda?</p><p>El proyecto evolucionó de un mockup visual hacia una plataforma que busca conectar orientación, seguimiento, documentos, asesores y servicios oficiales en una sola experiencia.</p></ContentCard>
    <ContentCard id="mision" icon={Target} title="2. Misión y visión"><p><strong>Misión:</strong> ayudar a las personas a realizar sus trámites con información comprensible, rutas claras y acompañamiento oportuno.</p><p><strong>Visión:</strong> convertirnos en el copiloto digital de confianza para trámites en el Perú y, posteriormente, en Latinoamérica.</p></ContentCard>
    <ContentCard id="principios" icon={ShieldCheck} title="3. Nuestros principios"><div className="grid gap-3 sm:grid-cols-2">{[[Compass,'Claridad primero','Explicamos qué hacer sin lenguaje innecesariamente complicado.'],[HeartHandshake,'Control del usuario','Tú decides si avanzas por tu cuenta o solicitas apoyo.'],[ShieldCheck,'Privacidad desde el diseño','Pedimos solo los datos necesarios y protegemos los sensibles.'],[Accessibility,'Diseño para todos','Creamos experiencias accesibles y responsive.']].map(([Icon,title,text]:any)=><div key={title} className="rounded-xl border border-blue-100 bg-blue-50/50 p-4"><Icon size={23} className="text-blue-700"/><h3 className="mt-2 font-extrabold text-slate-950">{title}</h3><p className="mt-1 text-xs leading-5">{text}</p></div>)}</div></ContentCard>
    <ContentCard id="producto" icon={Compass} title="4. Qué estamos construyendo"><ul><li>Un catálogo confiable de trámites, requisitos, costos y fuentes.</li><li>Rutas guiadas y checklists que reduzcan errores.</li><li>Alertas, seguimiento y conservación segura de evidencias.</li><li>Delegación responsable con asesores especializados.</li><li>APIs documentadas para futuras aplicaciones móviles y aliados.</li></ul></ContentCard>
    <ContentCard id="equipo" icon={UsersRound} title="5. Equipo y datos institucionales"><p>Para esta etapa demostrativa usamos datos institucionales temporales: <strong>TramIA Labs Perú</strong>, Lima, Perú; contacto: <a href="mailto:davsan82@gmail.com">davsan82@gmail.com</a>.</p><p>La razón social, RUC, domicilio, equipo público y canales corporativos serán reemplazados antes del lanzamiento comercial.</p></ContentCard>
  </InstitutionalLayout>;
}
