import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Check, FileText, LoaderCircle, Trash2, Upload, X } from 'lucide-react';
import { confirmTramia } from './TramiaDialog';

type DocumentItem={id:string;originalFileName:string;mimeType:string;sizeBytes:number;status:string;createdAt:string};

export default function CaseDocuments({caseId,role}:{caseId:string;role:'owner'|'advisor'}){
  const[items,setItems]=useState<DocumentItem[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
  const inputRef=useRef<HTMLInputElement>(null);
  const load=useCallback(async()=>{setLoading(true);const r=await fetch(`/api/v1/procedure-cases/${caseId}/documents`,{credentials:'include'}),p=await r.json().catch(()=>({}));if(r.ok){setItems(p.documents||[]);setError('')}else setError(p.message||'No pudimos cargar los documentos.');setLoading(false)},[caseId]);
  useEffect(()=>{void load()},[load]);
  const upload=async(file?:File)=>{if(!file)return;setSaving(true);setError('');try{const contentBase64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=()=>reject(new Error('No pudimos leer el archivo.'));reader.readAsDataURL(file)});const r=await fetch(`/api/v1/procedure-cases/${caseId}/documents`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({fileName:file.name,mimeType:file.type,contentBase64})}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.message||'No pudimos subir el documento.');await load()}catch(e){setError(e instanceof Error?e.message:'No pudimos subir el documento.')}finally{setSaving(false);if(inputRef.current)inputRef.current.value=''}};
  const review=async(id:string,status:'approved'|'rejected')=>{await fetch(`/api/v1/documents/${id}/review`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});await load()};
  const remove=async(id:string)=>{if(!await confirmTramia({title:'¿Retirar este documento?',message:'El archivo dejará de estar disponible en este trámite.',variant:'danger',confirmLabel:'Sí, retirar',cancelLabel:'Conservar'}))return;await fetch(`/api/v1/documents/${id}`,{method:'DELETE',credentials:'include'});await load()};
  return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><h3 className="font-black">Documentos</h3><p className="mt-1 text-xs text-slate-500">PDF, JPG o PNG de hasta 8 MB.</p></div>{role==='owner'&&<><input ref={inputRef} type="file" accept=".pdf,.jpg,.jpeg,.png" className="hidden" onChange={e=>void upload(e.target.files?.[0])}/><button onClick={()=>inputRef.current?.click()} disabled={saving} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-blue-600 px-3 text-xs font-black text-white disabled:opacity-50">{saving?<LoaderCircle size={16} className="animate-spin"/>:<Upload size={16}/>} Subir</button></>}</div>{error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-xs font-bold text-red-700">{error}</p>}{loading?<LoaderCircle className="mx-auto my-8 animate-spin text-blue-600"/>:<div className="mt-4 space-y-2">{items.map(item=><article key={item.id} className="flex flex-wrap items-center gap-3 rounded-2xl bg-slate-50 p-3"><FileText size={18} className="text-blue-600"/><a href={`/api/v1/documents/${item.id}/content`} target="_blank" rel="noreferrer" className="min-w-0 flex-1 truncate text-xs font-black text-slate-700 hover:text-blue-700">{item.originalFileName}</a><span className={`rounded-full px-2 py-1 text-[10px] font-black ${item.status==='approved'?'bg-emerald-100 text-emerald-700':item.status==='rejected'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}`}>{item.status==='approved'?'Aprobado':item.status==='rejected'?'Por corregir':'Pendiente'}</span>{role==='advisor'&&<><button title="Aprobar" onClick={()=>void review(item.id,'approved')} className="grid size-8 place-items-center rounded-lg bg-emerald-100 text-emerald-700"><Check size={15}/></button><button title="Solicitar corrección" onClick={()=>void review(item.id,'rejected')} className="grid size-8 place-items-center rounded-lg bg-red-100 text-red-700"><X size={15}/></button></>}{role==='owner'&&<button title="Retirar" onClick={()=>void remove(item.id)} className="grid size-8 place-items-center rounded-lg text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={15}/></button>}</article>)}{!items.length&&<p className="py-6 text-center text-xs text-slate-500">Todavía no hay documentos adjuntos.</p>}</div>}</section>;
}
