import React, { useState } from 'react';
import { ArrowLeft, ArrowRight, Award, Building2, CheckCircle2, Clock3, ExternalLink, FileText, Globe2, HelpCircle, Layers3, MessageCircle, ShieldCheck, Sparkles, UserPlus, WalletCards, X } from 'lucide-react';
import type { Procedure, UserProfile } from '../types';
import ProcedureIcon from './ProcedureIcon';
import TramIABot from './TramIABot';

interface Props { procedure: Procedure; onBack:()=>void; onStartProcedure:(procedure:Procedure,isDelegated:boolean,authMode?:'login'|'signup')=>void; userProfile?:UserProfile|null; onTriggerLogin?:(mode?:'login'|'signup')=>void; }

export default function ModernProcedureDetailView({procedure,onBack,onStartProcedure,userProfile}:Props){
  const [chatOpen,setChatOpen]=useState(false); const [help,setHelp]=useState<{title:string;description:string}|null>(null);
  const officialUrl=procedure.officialUrl||'https://www.gob.pe';
  return <div className="min-h-screen bg-[#f4f8fd] pb-14 text-slate-950">
    <header className="border-b border-blue-100 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6 lg:px-8"><button onClick={onBack} className="inline-flex min-h-10 items-center gap-2 text-sm font-extrabold text-slate-600 hover:text-blue-700"><ArrowLeft size={17}/> Volver a trámites</button><span className="rounded-full bg-blue-50 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.14em] text-blue-700">{procedure.category}</span></div></header>
    <main className="mx-auto max-w-7xl space-y-6 px-4 py-7 sm:px-6 lg:px-8">
      <section className="relative isolate overflow-hidden rounded-[2rem] bg-[linear-gradient(125deg,#071a3d,#0d4db7_62%,#13afd1)] p-6 text-white shadow-[0_24px_70px_rgba(14,74,170,.22)] sm:p-8 lg:p-10"><div className="absolute inset-0 -z-10 opacity-20 bg-[radial-gradient(circle_at_1px_1px,white_1px,transparent_0)] bg-size-[24px_24px]"/><div className="grid gap-7 lg:grid-cols-[1fr_290px] lg:items-center"><div><div className="flex items-center gap-4"><ProcedureIcon category={procedure.category} title={procedure.title} size={36}/><div><p className="text-xs font-black uppercase tracking-[.16em] text-cyan-200">Guía informativa del trámite</p><p className="mt-1 text-xs font-bold text-blue-100">Información del catálogo TramIA</p></div></div><h1 className="mt-6 max-w-4xl text-3xl font-black tracking-tight sm:text-4xl lg:text-5xl">{procedure.title}</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-blue-50 sm:text-base">{procedure.description}</p><div className="mt-6 flex flex-wrap gap-3"><a href={officialUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-white px-5 text-sm font-black text-blue-700 hover:bg-blue-50">Ir a la web oficial <ExternalLink size={16}/></a><button onClick={()=>setChatOpen(true)} className="inline-flex min-h-12 items-center gap-2 rounded-xl border border-white/30 bg-white/10 px-5 text-sm font-black text-white backdrop-blur hover:bg-white/20"><MessageCircle size={17}/> Preguntar al TramIA Copilot</button></div></div><div className="relative hidden min-h-64 lg:block"><div className="absolute right-0 top-0 rounded-2xl border border-white/20 bg-white/10 p-4 text-xs font-bold backdrop-blur">¿Tienes dudas?<br/><span className="text-cyan-200">Conversemos sobre este trámite.</span></div><img src="/assets/mascot/tramia-bot-contact.png" alt="TramIA Copilot atiende tus consultas" className="absolute bottom-[-40px] right-8 h-64 object-contain drop-shadow-[0_20px_30px_rgba(0,0,0,.3)]"/></div></div></section>

      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Quick icon={Globe2} label="Tipo de trámite" value="Estatal"/><Quick icon={Building2} label="Entidad" value={procedure.entity||'Entidad competente'}/><Quick icon={Clock3} label="Duración" value={procedure.estimatedDuration||procedure.duration}/><Quick icon={WalletCards} label="Tasa del Estado" value={procedure.estimatedCost}/><Quick icon={Award} label="Dificultad" value={procedure.complexity}/></section>

      {!userProfile?<section className="relative overflow-hidden rounded-3xl bg-slate-950 p-6 text-white sm:p-8"><div className="absolute -right-16 -top-20 size-64 rounded-full bg-blue-600/30 blur-3xl"/><div className="relative flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div className="flex max-w-3xl gap-4"><span className="hidden size-12 shrink-0 place-items-center rounded-2xl bg-blue-600 sm:grid"><UserPlus/></span><div><p className="text-xs font-black uppercase tracking-[.15em] text-cyan-300">Convierte esta guía en tu ruta personal</p><h2 className="mt-2 text-2xl font-black">Gestiona el trámite paso a paso con TramIA</h2><p className="mt-2 text-sm leading-6 text-slate-300">Crea una cuenta gratis para guardar tu avance, organizar documentos y recibir alertas.</p></div></div><div className="shrink-0 text-center"><button onClick={()=>onStartProcedure(procedure,false,'signup')} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-black hover:bg-blue-500">Crear cuenta gratis <ArrowRight size={16}/></button><p className="mt-2 text-[11px] text-slate-400">¿Ya tienes cuenta? <button onClick={()=>onStartProcedure(procedure,false,'login')} className="font-black text-cyan-300 hover:underline">Inicia sesión</button></p></div></div></section>:<section className="relative overflow-hidden rounded-[1.75rem] border border-blue-200 bg-[linear-gradient(105deg,#ffffff_0%,#eff6ff_48%,#ddfbff_100%)] p-5 shadow-[0_14px_40px_rgba(14,84,190,.10)] sm:p-6"><div className="absolute -right-12 -top-16 size-48 rounded-full bg-cyan-300/25 blur-3xl"/><div className="relative flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div className="flex max-w-3xl items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-blue-600 text-white shadow-lg shadow-blue-600/20"><CheckCircle2 size={23}/></span><div><p className="text-[11px] font-black uppercase tracking-[.16em] text-blue-700">Convierte esta guía en una ruta activa</p><h2 className="mt-1 text-xl font-black sm:text-2xl">Empieza este trámite con TramIA</h2><p className="mt-2 text-sm leading-6 text-slate-600">Elige si quieres avanzar con nuestra guía paso a paso o solicitar apoyo especializado.</p></div></div><button onClick={()=>onStartProcedure(procedure,false)} className="group inline-flex min-h-13 shrink-0 items-center justify-center gap-3 rounded-2xl bg-blue-600 px-6 text-sm font-black text-white shadow-lg shadow-blue-600/25 transition hover:-translate-y-0.5 hover:bg-blue-700 hover:shadow-xl">Elegir cómo empezar <ArrowRight size={17} className="transition-transform group-hover:translate-x-1"/></button></div></section>}

      <section className="grid gap-4 lg:grid-cols-2"><article className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-blue-50 text-blue-700"><ShieldCheck/></span><div><p className="text-[10px] font-black uppercase tracking-[.15em] text-blue-600">Fuente oficial</p><h2 className="text-lg font-black">{procedure.entity||'Plataforma del Estado Peruano'}</h2></div></div><p className="mt-4 text-sm leading-6 text-slate-600">Verifica las condiciones vigentes, tasas y canales de atención directamente en la entidad responsable.</p><a href={officialUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-blue-200 text-xs font-black text-blue-700 hover:bg-blue-50">Consultar fuente oficial <ExternalLink size={15}/></a></article><article className="relative overflow-hidden rounded-3xl border border-cyan-200 bg-[linear-gradient(135deg,#eff8ff,#e8fdff)] p-6"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-blue-600 text-white"><Sparkles/></span><div><p className="text-[10px] font-black uppercase tracking-[.15em] text-blue-600">TramIA Copilot · Demo</p><h2 className="text-lg font-black">Resuelve dudas antes de empezar</h2></div></div><p className="mt-4 text-sm leading-6 text-slate-600">Pregunta por requisitos, duración, costos o por cualquiera de los pasos de esta ruta.</p><button onClick={()=>setChatOpen(true)} className="mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-blue-600 text-xs font-black text-white hover:bg-blue-700"><MessageCircle size={15}/> Abrir chat del trámite</button></article></section>

      <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-8" id="procedure-route-section"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.15em] text-blue-600"><Layers3 size={16}/> Ruta del procedimiento</p><h2 className="mt-2 text-2xl font-black">Tu guía paso a paso</h2><p className="mt-1 text-sm text-slate-500">Revisa cada etapa antes de iniciar. Las condiciones pueden variar según tu caso.</p></div><span className="text-xs font-bold text-slate-500">{procedure.steps.length} pasos</span></div><div className="relative mt-8 space-y-4 before:absolute before:bottom-7 before:left-[19px] before:top-7 before:w-0.5 before:bg-blue-100 sm:before:left-[23px]">{procedure.steps.map((step,index)=>{const requirements=procedure.requirements.filter(r=>r.requiredForStepId===step.id);return <article key={step.id} className="relative pl-14 sm:pl-16"><span className="absolute left-0 top-5 z-10 grid size-10 place-items-center rounded-full border-2 border-blue-500 bg-white text-sm font-black text-blue-700 shadow-sm sm:size-12">{index+1}</span><div className="rounded-2xl border border-slate-200 bg-slate-50/50 p-5 transition hover:border-blue-300 hover:bg-white hover:shadow-md"><div className="flex items-start justify-between gap-3"><div><h3 className="text-base font-black">{step.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{step.description}</p></div><button onClick={()=>setHelp({title:step.title,description:step.description})} aria-label={`Ayuda sobre ${step.title}`} className="grid size-9 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-700 hover:bg-blue-100"><HelpCircle size={18}/></button></div>{requirements.length>0&&<div className="mt-4 border-t border-slate-200 pt-4"><p className="text-[10px] font-black uppercase tracking-[.14em] text-slate-400">Documentos o requisitos</p><div className="mt-2 flex flex-wrap gap-2">{requirements.map(req=><button key={req.id} onClick={()=>setHelp({title:req.name,description:req.description})} className="inline-flex items-center gap-2 rounded-xl border border-blue-200 bg-white px-3 py-2 text-xs font-bold text-blue-700 hover:bg-blue-50"><FileText size={14}/>{req.name}<Sparkles size={12}/></button>)}</div></div>}<div className="mt-4 flex flex-wrap gap-3 border-t border-slate-200 pt-4"><a href={step.actionUrl||officialUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-xs font-black text-blue-700">Ir al canal oficial <ExternalLink size={14}/></a><button onClick={()=>setChatOpen(true)} className="inline-flex items-center gap-2 text-xs font-black text-cyan-700"><MessageCircle size={14}/> Preguntar al Copilot</button></div></div></article>})}</div></section>
    </main>
    <TramIABot procedure={procedure} requirements={procedure.requirements} isPaid={false} advisorName="Copiloto de orientación" isOpen={chatOpen} onClose={()=>setChatOpen(false)}/>
    {help&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4 backdrop-blur-sm" onClick={()=>setHelp(null)}><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-4"><span className="grid size-12 place-items-center rounded-2xl bg-blue-50 text-blue-700"><Sparkles/></span><button onClick={()=>setHelp(null)} className="grid size-9 place-items-center rounded-full bg-slate-100"><X size={18}/></button></div><p className="mt-5 text-xs font-black uppercase tracking-[.14em] text-blue-600">Ayuda de TramIA Copilot</p><h2 className="mt-2 text-xl font-black">{help.title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{help.description}</p><button onClick={()=>{setHelp(null);setChatOpen(true)}} className="mt-6 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-blue-600 text-sm font-black text-white"><MessageCircle size={16}/> Hacer otra pregunta</button></div></div>}
  </div>
}

function Quick({icon:Icon,label,value}:{icon:React.ElementType;label:string;value:string}){return <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><Icon size={19}/></span><p className="mt-3 text-[10px] font-black uppercase tracking-[.12em] text-slate-400">{label}</p><p className="mt-1 text-sm font-black leading-5">{value}</p></article>}
