import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowRight, Award, CalendarDays, CheckCircle2, Clock3, CreditCard, FileText, Medal, RefreshCw, Sparkles, Star, Trophy, UserRoundCheck, X } from 'lucide-react';
import CaseDocuments from './CaseDocuments';
import CaseMessages from './CaseMessages';
import DelegationModalV2 from './DelegationModalV2';
import ProcedureHistoryDetailModal from './ProcedureHistoryDetailModal';

type ProcedureItem = {
  id: string; procedureId: string; trackingCode: string; title: string; category: string;
  mode: 'self_service' | 'delegated' | 'hybrid'; status: string; progressPercentage: number;
  startedAt?: string | null; expectedCompletionAt?: string | null; completedAt?: string | null; cancelledAt?: string | null; updatedAt: string;
  advisorId?: string | null; advisorName?: string | null; advisorAverageRating?: string | null; advisorCompletedCases?: number | null;
  userRating?: number | null; ratingComment?: string | null;
};
type Summary = { activeCount: number; completedCount: number; cancelledCount: number; delegatedCompletedCount: number; ratedAdvisorsCount: number; totalCount: number };
const emptySummary: Summary = { activeCount: 0, completedCount: 0, cancelledCount: 0, delegatedCompletedCount: 0, ratedAdvisorsCount: 0, totalCount: 0 };
const statusLabel: Record<string, string> = { draft:'Por iniciar', active:'Activo', waiting_user:'Necesita tu atención', eligible_for_delegation:'Listo para delegar', waiting_payment:'Pago pendiente', waiting_assignment:'Buscando asesor', delegated:'Delegado', in_progress:'En proceso', paused:'Pausado', completed:'Completado', cancelled:'Cancelado', rejected:'No aprobado' };
const formatDate = (value?: string | null) => value ? new Intl.DateTimeFormat('es-PE', { day:'2-digit', month:'short', year:'numeric' }).format(new Date(value)) : 'Sin fecha';

export default function MyProceduresView({ onOpenProcedure, onExplore, onSummaryChange }: { onOpenProcedure:(procedureId:string,userProcedureId:string)=>void; onExplore:()=>void; onSummaryChange?:(summary:Summary)=>void }) {
  const [active, setActive] = useState<ProcedureItem[]>([]), [history, setHistory] = useState<ProcedureItem[]>([]), [summary, setSummary] = useState<Summary>(emptySummary);
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [ratingItem, setRatingItem] = useState<ProcedureItem|null>(null),[delegationItem,setDelegationItem]=useState<ProcedureItem|null>(null),[toolsItem,setToolsItem]=useState<ProcedureItem|null>(null),[historyDetailId,setHistoryDetailId]=useState<string|null>(null);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response=await fetch('/api/v1/my-procedures',{credentials:'include'}); const contentType=response.headers.get('content-type')||''; if(!contentType.includes('application/json')) throw new Error('El servidor local necesita reiniciarse para habilitar esta sección.'); const payload=await response.json(); if(!response.ok) throw new Error(payload.message||'No pudimos cargar tus trámites.'); setActive(payload.data.active||[]); setHistory(payload.data.history||[]); setSummary(payload.summary||emptySummary); } catch(e) { setError(e instanceof Error?e.message:'No pudimos cargar tus trámites.'); } finally { setLoading(false); } },[]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{onSummaryChange?.(summary)},[summary,onSummaryChange]);
  const level = useMemo(()=> summary.completedCount >= 10 ? 3 : summary.completedCount >= 3 ? 2 : 1,[summary.completedCount]);
  const nextGoal = level===1?3:level===2?10:25, achievementProgress=Math.min(100,(summary.completedCount/nextGoal)*100);
  const medals = [
    { icon:Sparkles, name:'Primer paso', detail:'Inicia tu primer trámite', earned:summary.totalCount>=1 },
    { icon:Medal, name:'Buen tramitador', detail:'Completa 3 trámites', earned:summary.completedCount>=3 },
    { icon:UserRoundCheck, name:'Gestión acompañada', detail:'Finaliza un trámite delegado', earned:summary.delegatedCompletedCount>=1 },
    { icon:Trophy, name:'Experto TramIA', detail:'Completa 10 trámites', earned:summary.completedCount>=10 },
  ];

  return <div className="mx-auto max-w-6xl space-y-8 animate-fadeIn">
    <section className="relative overflow-hidden rounded-[2rem] bg-[linear-gradient(120deg,#071a3d,#0e55c7_62%,#13afd1)] p-6 text-white shadow-xl shadow-blue-950/10 sm:p-8">
      <div className="absolute inset-0 opacity-20" style={{backgroundImage:'radial-gradient(circle at 1px 1px,white 1px,transparent 0)',backgroundSize:'22px 22px'}} />
      <div className="relative grid items-center gap-6 lg:grid-cols-[1fr_250px]">
        <div><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-200">Tu espacio TramIA</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Mis trámites</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-blue-100">Organiza tus gestiones, continúa donde las dejaste y construye tu perfil de buen tramitador.</p>
          <div className="mt-6 grid grid-cols-2 gap-2 sm:max-w-2xl sm:grid-cols-4 sm:gap-3">{[[summary.activeCount,'Activos'],[summary.completedCount,'Completados'],[summary.cancelledCount,'Cancelados'],[summary.totalCount,'En total']].map(([value,label])=><div key={label} className="rounded-2xl border border-white/15 bg-white/10 p-3 backdrop-blur"><strong className="block text-2xl font-black">{value}</strong><span className="text-[11px] font-bold text-blue-100">{label}</span></div>)}</div>
        </div>
        <img src="/assets/mascot/tramia-bot-superhero.png" alt="TramIA Bot celebrando tus logros" className="mx-auto hidden h-52 w-52 object-contain drop-shadow-2xl lg:block" />
      </div>
    </section>

    <section className="grid gap-5 lg:grid-cols-[1fr_1.45fr]">
      <div className="rounded-3xl border border-blue-100 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-blue-50 text-blue-600"><Award size={25}/></span><div><p className="text-[11px] font-black uppercase tracking-widest text-blue-600">Perfil tramitador</p><h2 className="text-xl font-black text-slate-950">Nivel {level}</h2></div></div><p className="mt-4 text-sm text-slate-600">Cada trámite completado desbloquea nuevos reconocimientos en tu perfil.</p><div className="mt-4"><div className="flex justify-between text-xs font-bold text-slate-600"><span>{summary.completedCount} completados</span><span>Meta: {nextGoal}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[linear-gradient(90deg,#1769e0,#19b9d6)]" style={{width:`${achievementProgress}%`}}/></div></div></div>
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{medals.map(({icon:Icon,name,detail,earned})=><div key={name} className={`rounded-3xl border p-4 text-center ${earned?'border-cyan-200 bg-cyan-50':'border-slate-200 bg-slate-50 opacity-55'}`}><span className={`mx-auto grid size-14 place-items-center rounded-2xl ${earned?'bg-white text-blue-600 shadow-sm':'bg-slate-200 text-slate-400'}`}><Icon size={28}/></span><h3 className="mt-3 text-xs font-black text-slate-900">{name}</h3><p className="mt-1 text-[10px] leading-4 text-slate-500">{earned?'Logro obtenido':detail}</p></div>)}</div>
    </section>

    {error&&<div className="flex flex-col items-center gap-3 rounded-2xl border border-red-200 bg-red-50 p-5 text-center text-sm font-bold text-red-700"><span>{error}</span><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2"><RefreshCw size={15}/>Reintentar</button></div>}
    <section className="space-y-4"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-600">En marcha</p><h2 className="mt-1 text-2xl font-black text-slate-950">Trámites actuales</h2><p className="mt-1 text-sm text-slate-500">Continúa tus gestiones y revisa el siguiente paso.</p></div>{active.length>0&&<span className="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-black text-blue-700">{active.length} activos</span>}</div>
      {loading?<LoadingCards/>:active.length===0?<EmptyState icon={Clock3} title="Todavía no tienes trámites activos" text="Explora el catálogo y empieza una ruta guiada cuando estés listo." action="Ver todos los trámites" onAction={onExplore}/>:<div className="grid gap-4 md:grid-cols-2">{active.map(item=><article key={item.id} className="group rounded-3xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-lg"><div className="flex items-start justify-between gap-3"><div><span className="text-[10px] font-black uppercase tracking-widest text-blue-600">{item.category}</span><h3 className="mt-1 text-lg font-black leading-snug text-slate-950">{item.title}</h3></div><span className="shrink-0 rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-black text-blue-700">{statusLabel[item.status]||item.status}</span></div><div className="mt-5"><div className="flex justify-between text-xs font-bold text-slate-500"><span>Avance</span><strong className="text-blue-700">{item.progressPercentage}%</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${item.progressPercentage}%`}}/></div></div><div className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-xs text-slate-500"><span className="inline-flex items-center gap-1.5"><FileText size={14}/>Código {item.trackingCode}</span><span className="inline-flex items-center gap-1.5"><CalendarDays size={14}/>{item.expectedCompletionAt?`Fecha estimada: ${formatDate(item.expectedCompletionAt)}`:`Actualizado: ${formatDate(item.updatedAt)}`}</span></div>{item.advisorName&&<div className="mt-4 rounded-2xl bg-cyan-50 p-3 text-xs text-slate-600"><strong className="text-slate-900">Asesor: {item.advisorName}</strong><span className="ml-2">★ {item.advisorAverageRating||'Nuevo'}</span></div>}<div className="mt-5 grid gap-2 sm:grid-cols-2"><button onClick={()=>onOpenProcedure(item.procedureId,item.id)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-black text-white shadow-lg shadow-blue-600/15">Continuar trámite <ArrowRight size={17}/></button>{item.mode==='self_service'&&['active','eligible_for_delegation','waiting_user'].includes(item.status)&&<button onClick={()=>setDelegationItem(item)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-cyan-200 bg-cyan-50 px-4 text-sm font-black text-blue-800"><UserRoundCheck size={17}/>Delegar</button>}{['waiting_payment','waiting_assignment'].includes(item.status)&&<button onClick={()=>setDelegationItem(item)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-amber-200 bg-amber-50 px-4 text-sm font-black text-amber-800"><CreditCard size={17}/>{item.status==='waiting_payment'?'Completar pago':'Ver solicitud'}</button>}</div></article>)}</div>}
    </section>

    <section className="space-y-4 pb-5"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-600">Tu recorrido</p><h2 className="mt-1 text-2xl font-black text-slate-950">Historial de trámites</h2><p className="mt-1 text-sm text-slate-500">Consulta tus gestiones finalizadas, canceladas o no aprobadas.</p></div>
      {!loading&&history.length===0?<EmptyState icon={CheckCircle2} title="Tu historial está vacío" text="Cuando finalices o cierres un trámite, aparecerá aquí con su información."/>:<div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">{history.map(item=><article key={item.id} className="grid gap-4 border-b border-slate-100 p-5 last:border-0 md:grid-cols-[1fr_auto] md:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${item.status==='completed'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{statusLabel[item.status]||item.status}</span><span className="text-[10px] font-black uppercase tracking-widest text-slate-400">{item.category}</span></div><h3 className="mt-2 font-black text-slate-950">{item.title}</h3><p className="mt-1 text-xs text-slate-500">{item.status==='completed'?`Completado: ${formatDate(item.completedAt)}`:`Última actualización: ${formatDate(item.updatedAt)}`} · {item.mode==='self_service'?'Autogestionado':'Gestión con asesor'}</p>{item.advisorName&&<p className="mt-2 text-xs font-bold text-blue-700">Asesor: {item.advisorName}</p>}</div><div className="flex flex-wrap gap-2 md:justify-end">{item.status==='completed'&&item.advisorId&&(item.userRating?<span className="inline-flex min-h-10 items-center gap-1.5 rounded-xl border border-amber-200 bg-amber-50 px-3 text-xs font-black text-amber-800"><Star size={15} fill="currentColor"/>{item.userRating}/5 · Calificación enviada</span>:<button onClick={()=>setRatingItem(item)} className="inline-flex min-h-10 items-center gap-1.5 rounded-xl border border-amber-200 bg-amber-50 px-3 text-xs font-black text-amber-800"><Star size={15}/>Calificar asesor</button>)}<button onClick={()=>setHistoryDetailId(item.id)} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-blue-200 px-3 text-xs font-black text-blue-700">Ver detalle <ArrowRight size={14}/></button></div></article>)}</div>}
    </section>
    {ratingItem&&<RatingModal item={ratingItem} onClose={()=>setRatingItem(null)} onSaved={()=>{setRatingItem(null);void load()}}/>}
    {toolsItem&&<CaseToolsModal item={toolsItem} onClose={()=>setToolsItem(null)}/>}
    {delegationItem&&<DelegationModalV2 item={delegationItem} onClose={()=>setDelegationItem(null)} onSaved={()=>{setDelegationItem(null);void load()}}/>}
    {historyDetailId&&<ProcedureHistoryDetailModal caseId={historyDetailId} onClose={()=>setHistoryDetailId(null)}/>}
  </div>;
}

function CaseToolsModal({item,onClose}:{item:ProcedureItem;onClose:()=>void}){return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/65 p-4 backdrop-blur-sm"><div className="mx-auto my-6 w-full max-w-3xl rounded-[2rem] bg-slate-100 p-5 shadow-2xl"><div className="mb-5 flex justify-between"><div><p className="text-[10px] font-black uppercase tracking-widest text-blue-600">{item.trackingCode}</p><h2 className="text-xl font-black">Documentos y conversación</h2></div><button onClick={onClose} className="grid size-10 place-items-center rounded-full bg-white"><X size={18}/></button></div><div className="space-y-5"><CaseDocuments caseId={item.id} role="owner"/><CaseMessages caseId={item.id}/></div></div></div>}
function LoadingCards(){return <div className="grid gap-4 md:grid-cols-2">{[0,1].map(i=><div key={i} className="h-64 animate-pulse rounded-3xl bg-slate-100"/>)}</div>}
function EmptyState({icon:Icon,title,text,action,onAction}:{icon:React.ElementType;title:string;text:string;action?:string;onAction?:()=>void}){return <div className="rounded-3xl border border-dashed border-blue-200 bg-[linear-gradient(135deg,#fff,#f0f8ff)] p-8 text-center"><span className="mx-auto grid size-16 place-items-center rounded-2xl bg-blue-50 text-blue-600"><Icon size={30}/></span><h3 className="mt-4 text-lg font-black text-slate-950">{title}</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">{text}</p>{action&&<button onClick={onAction} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-black text-white">{action}<ArrowRight size={16}/></button>}</div>}
function RatingModal({item,onClose,onSaved}:{item:ProcedureItem;onClose:()=>void;onSaved:()=>void}) {
  const [stars,setStars]=useState(0),[hover,setHover]=useState(0),[comment,setComment]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
  const save=async()=>{if(!stars){setError('Selecciona de 1 a 5 estrellas. Puedes usar medias estrellas.');return}setSaving(true);setError('');try{const response=await fetch(`/api/v1/my-procedures/${item.id}/rating`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({rating:stars,comment})});const payload=await response.json();if(!response.ok)throw new Error(payload.message||'No pudimos guardar tu calificación.');onSaved()}catch(e){setError(e instanceof Error?e.message:'No pudimos guardar tu calificación.')}finally{setSaving(false)}};
  const visibleRating=hover||stars;
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="advisor-rating-title"><div className="w-full max-w-md rounded-[2rem] bg-white p-6 shadow-2xl sm:p-8"><span className="grid size-14 place-items-center rounded-2xl bg-amber-50 text-amber-500"><Star size={28}/></span><h2 id="advisor-rating-title" className="mt-4 text-2xl font-black text-slate-950">Califica a tu asesor</h2><p className="mt-2 text-sm text-slate-500">Tu experiencia con <strong>{item.advisorName}</strong> ayudará a mantener una comunidad de asesores confiable.</p><div className="mt-5"><HalfStarRating value={stars} preview={hover} onPreview={setHover} onChange={setStars}/><p className="mt-2 text-center text-xs font-black text-amber-700">{visibleRating ? `${visibleRating} de 5 estrellas` : 'Selecciona tu calificación'}</p></div><textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={1000} placeholder="Cuéntanos cómo fue la atención (opcional)" className="mt-5 min-h-28 w-full rounded-2xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-100"/><p className="mt-2 text-[11px] leading-4 text-slate-500">Revisa tu selección antes de enviarla. La calificación quedará registrada y no podrá modificarse.</p>{error&&<p className="mt-2 text-xs font-bold text-red-600">{error}</p>}<div className="mt-5 grid grid-cols-2 gap-3"><button type="button" onClick={onClose} disabled={saving} className="min-h-11 rounded-xl bg-slate-100 text-sm font-black text-slate-700">Cancelar</button><button type="button" onClick={()=>void save()} disabled={saving||!stars} className="min-h-11 rounded-xl bg-blue-600 text-sm font-black text-white disabled:opacity-45">{saving?'Guardando...':'Enviar calificación'}</button></div></div></div>;
}

function HalfStarRating({value,preview,onPreview,onChange}:{value:number;preview:number;onPreview:(value:number)=>void;onChange:(value:number)=>void}) {
  const visible=preview||value;
  return <div className="flex justify-center gap-1" onMouseLeave={()=>onPreview(0)}>{[1,2,3,4,5].map(index=>{const fill=visible>=index?100:visible>=index-.5?50:0;return <span key={index} className="relative block size-11 text-slate-200"><Star className="absolute inset-0 size-11" fill="currentColor"/><span className="pointer-events-none absolute inset-0 overflow-hidden text-amber-400" style={{width:`${fill}%`}}><Star className="absolute inset-0 size-11 max-w-none" fill="currentColor"/></span><button type="button" aria-label={`${index-.5} estrellas`} onMouseEnter={()=>onPreview(index-.5)} onFocus={()=>onPreview(index-.5)} onClick={()=>onChange(index-.5)} className="absolute inset-y-0 left-0 z-10 w-1/2"/><button type="button" aria-label={`${index} estrellas`} onMouseEnter={()=>onPreview(index)} onFocus={()=>onPreview(index)} onClick={()=>onChange(index)} className="absolute inset-y-0 right-0 z-10 w-1/2"/></span>})}</div>;
}
