import React, { useEffect, useState } from 'react';
import { AlertCircle, ArrowRight, CheckCircle2, Clock3, Eye, EyeOff, KeyRound, LoaderCircle, LockKeyhole, LogIn, RotateCcw } from 'lucide-react';
import TramIALogo from './TramIALogo';

type Status = 'checking'|'ready'|'saving'|'success'|'expired'|'used'|'invalid'|'error';

export default function PasswordResetView({onLogin,onRequestNew}:{onLogin:()=>void;onRequestNew:()=>void}) {
  const token = new URLSearchParams(window.location.search).get('token') || '';
  const [status,setStatus]=useState<Status>('checking'),[message,setMessage]=useState('Estamos revisando tu enlace seguro.'),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[show,setShow]=useState(false);
  useEffect(()=>{if(!token){setStatus('invalid');setMessage('El enlace está incompleto. Abre nuevamente el enlace completo recibido por correo.');return}fetch(`/api/v1/auth/reset-password/status?token=${encodeURIComponent(token)}`).then(async response=>{const result=await response.json().catch(()=>({}));if(response.ok){setStatus('ready');setMessage('Crea una nueva contraseña para tu cuenta. La actual seguirá funcionando hasta que confirmes el cambio.');return}setStatus(result.error==='expired_token'?'expired':result.error==='used_token'?'used':'invalid');setMessage(result.message||'No pudimos validar este enlace.');}).catch(()=>{setStatus('error');setMessage('No pudimos conectarnos con TramIA. Inténtalo nuevamente.');})},[token]);
  async function submit(event:React.FormEvent){event.preventDefault();if(password.length<8){setMessage('La nueva contraseña debe tener al menos 8 caracteres.');return}if(password!==confirm){setMessage('Las contraseñas no coinciden.');return}setStatus('saving');setMessage('Actualizando tu contraseña de forma segura…');try{const response=await fetch('/api/v1/auth/reset-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,password})});const result=await response.json().catch(()=>({}));if(!response.ok){setStatus(result.error==='expired_token'?'expired':result.error==='used_token'?'used':'error');setMessage(result.message||'No pudimos cambiar tu contraseña.');return}setStatus('success');setMessage(result.message)}catch{setStatus('error');setMessage('No pudimos conectarnos con TramIA. Inténtalo nuevamente.')}}
  const success=status==='success', unavailable=['expired','used','invalid'].includes(status), Icon=status==='checking'||status==='saving'?LoaderCircle:success?CheckCircle2:status==='expired'?Clock3:unavailable||status==='error'?AlertCircle:KeyRound;
  return <div className="min-h-[calc(100vh-72px)] bg-[radial-gradient(circle_at_top,#dff6ff_0,#eef6ff_34%,#fff_75%)] px-4 py-10 sm:py-14"><section className="mx-auto grid max-w-4xl overflow-hidden rounded-[2rem] border border-blue-100 bg-white shadow-[0_28px_80px_rgba(8,45,110,.16)] md:grid-cols-[.78fr_1.22fr]"><aside className="relative hidden overflow-hidden bg-[linear-gradient(145deg,#071a3d,#0d47a1_58%,#11a9cf)] p-7 text-white md:flex md:flex-col"><div className="absolute inset-0 opacity-20 bg-[radial-gradient(circle_at_1px_1px,white_1px,transparent_0)] bg-size-[24px_24px]"/><div className="relative"><TramIALogo iconSize={36} textSize="text-2xl" variant="dark"/><p className="mt-5 text-sm font-bold text-cyan-100">Protegemos el acceso a tu cuenta.</p></div><img src={success?'/assets/mascot/tramia-bot-guiding.png':'/assets/mascot/tramia-bot-reading.png'} alt="TramIA protege tu cambio de contraseña" className="relative my-auto max-h-72 w-full object-contain"/><p className="relative text-xs leading-5 text-blue-100">El enlace solo sirve para cambiar tu contraseña. Solicitarlo no bloquea tu cuenta ni invalida tu clave actual.</p></aside><main className="p-6 sm:p-9 md:p-11"><div className="md:hidden"><TramIALogo iconSize={34} textSize="text-2xl" variant="light"/></div><span className={`mt-6 grid size-14 place-items-center rounded-2xl md:mt-0 ${success?'bg-emerald-100 text-emerald-600':unavailable||status==='error'?'bg-red-100 text-red-600':'bg-blue-100 text-blue-600'}`}><Icon className={status==='checking'||status==='saving'?'animate-spin':''} size={27}/></span><p className="mt-5 text-xs font-black uppercase tracking-[.16em] text-blue-600">Recupera tu acceso</p><h1 className="mt-2 text-3xl font-black text-slate-950">{success?'Contraseña actualizada':status==='expired'?'El enlace venció':status==='used'?'Enlace ya utilizado':status==='invalid'?'Enlace no válido':'Crea una nueva contraseña'}</h1><p className={`mt-3 text-sm leading-6 ${status==='error'||unavailable?'text-red-700':'text-slate-600'}`}>{message}</p>
  {status==='ready'&&<form onSubmit={submit} className="mt-6 space-y-4"><PasswordField label="Nueva contraseña" value={password} onChange={setPassword} show={show} onToggle={()=>setShow(v=>!v)}/><PasswordField label="Confirmar contraseña" value={confirm} onChange={setConfirm} show={show} onToggle={()=>setShow(v=>!v)}/><div className="flex gap-3 rounded-2xl bg-blue-50 p-4 text-xs leading-5 text-blue-900"><LockKeyhole size={19} className="shrink-0 text-blue-600"/><p>Al confirmar, cerraremos las sesiones anteriores. Después ingresarás nuevamente con tu nueva contraseña.</p></div><button className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-black text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700">Cambiar mi contraseña <ArrowRight size={17}/></button></form>}
  {status==='saving'&&<div className="mt-6 h-12 animate-pulse rounded-xl bg-blue-100"/>}
  {(success||unavailable||status==='error')&&<div className="mt-7 flex flex-col gap-3 sm:flex-row">{success?<button onClick={onLogin} className="inline-flex min-h-12 flex-1 items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-black text-white"><LogIn size={17}/> Iniciar sesión</button>:<button onClick={onRequestNew} className="inline-flex min-h-12 flex-1 items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-black text-white"><RotateCcw size={17}/> Solicitar otro enlace</button>}{status==='error'&&<button onClick={()=>window.location.reload()} className="min-h-12 rounded-xl border border-blue-200 px-5 text-sm font-black text-blue-700">Reintentar</button>}</div>}</main></section></div>;
}

function PasswordField({label,value,onChange,show,onToggle}:{label:string;value:string;onChange:(value:string)=>void;show:boolean;onToggle:()=>void}){return <label className="block"><span className="mb-1.5 flex items-center gap-2 text-xs font-black text-slate-700"><KeyRound size={15} className="text-blue-600"/>{label}</span><div className="relative"><input type={show?'text':'password'} value={value} onChange={event=>onChange(event.target.value)} required minLength={8} autoComplete="new-password" className="field-input pr-11" placeholder="Mínimo 8 caracteres"/><button type="button" onClick={onToggle} aria-label={show?'Ocultar contraseña':'Mostrar contraseña'} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-blue-700">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>}
