import { AlertTriangle, Ban, CreditCard, FileText, Gavel, Scale, ShieldCheck, UserCheck } from 'lucide-react';
import InstitutionalLayout, { ContentCard } from './InstitutionalLayout';
export default function TermsView({ onBack }: { onBack: () => void }) {
  const sections=[{id:'aceptacion',label:'1. Aceptación'},{id:'servicio',label:'2. El servicio'},{id:'cuenta',label:'3. Tu cuenta'},{id:'responsabilidades',label:'4. Responsabilidades'},{id:'pagos',label:'5. Pagos'},{id:'propiedad',label:'6. Contenido'},{id:'limites',label:'7. Limitaciones'},{id:'cambios',label:'8. Cambios'}];
  return <InstitutionalLayout eyebrow="Reglas claras" title="Términos de uso" intro="Estas condiciones explican cómo puedes utilizar TramIA y cuáles son las responsabilidades de cada parte." mascot="/assets/mascot/tramia-bot-terms.png" mascotAlt="TramIA revisa y confirma los términos de uso" sections={sections} onBack={onBack} badge="Versión 0.1 · 12 de agosto de 2026">
    <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-900"><strong>Importante:</strong> TramIA brinda orientación y herramientas de gestión. No es una entidad pública y no garantiza la aprobación de un trámite.</div>
    <ContentCard id="aceptacion" icon={Scale} title="1. Aceptación"><p>Al crear una cuenta o utilizar TramIA aceptas estos términos y nuestra Política de Privacidad. Si no estás de acuerdo, no debes utilizar el servicio.</p><p>Para usar funciones que impliquen pagos o delegación debes ser mayor de edad y tener capacidad legal.</p></ContentCard>
    <ContentCard id="servicio" icon={FileText} title="2. Qué ofrece TramIA"><p>TramIA organiza información, requisitos, pasos, alertas y documentos; puede facilitar consultas externas y contacto con asesores. La información oficial puede cambiar, por lo que debes revisar la fuente indicada antes de pagar o presentar una solicitud.</p></ContentCard>
    <ContentCard id="cuenta" icon={UserCheck} title="3. Tu cuenta"><ul><li>Debes proporcionar información correcta y mantenerla actualizada.</li><li>Eres responsable de proteger tu contraseña y dispositivos.</li><li>No debes compartir credenciales de entidades públicas mediante TramIA.</li><li>Debes avisarnos si detectas un acceso no autorizado.</li></ul></ContentCard>
    <ContentCard id="responsabilidades" icon={ShieldCheck} title="4. Uso responsable"><p>No puedes usar la plataforma para suplantar identidades, cargar contenido ilícito, interferir con el servicio, extraer datos de forma automatizada sin autorización o perjudicar a otras personas.</p><p>Podemos suspender cuentas cuando exista riesgo, fraude, incumplimiento o una obligación legal.</p></ContentCard>
    <ContentCard id="pagos" icon={CreditCard} title="5. Pagos, delegación y cancelación"><p>Antes de pagar mostraremos el concepto, monto y proveedor. Las tasas de entidades y los servicios de delegación son conceptos distintos. No almacenamos PAN ni CVV.</p><p>Un trámite puede cancelarse, pero los pagos hechos a una entidad o el trabajo ya realizado por un asesor podrían no ser reembolsables. Las condiciones específicas se mostrarán antes de confirmar.</p></ContentCard>
    <ContentCard id="propiedad" icon={Gavel} title="6. Contenido y propiedad intelectual"><p>La marca, diseño, software y contenido original de TramIA están protegidos. La información pública pertenece a sus respectivas entidades y se presenta con fines de orientación y referencia.</p></ContentCard>
    <ContentCard id="limites" icon={AlertTriangle} title="7. Limitaciones"><p>TramIA no reemplaza asesoría legal, contable o profesional. No respondemos por cambios de una entidad, caídas de servicios externos, decisiones administrativas ni información incorrecta proporcionada por el usuario.</p><p>Nada limita los derechos que la legislación peruana reconoce al consumidor.</p></ContentCard>
    <ContentCard id="cambios" icon={Ban} title="8. Cambios, ley aplicable y contacto"><p>Podemos actualizar estos términos y comunicaremos los cambios relevantes. Se interpretan según las leyes del Perú. Para consultas escribe a <a href="mailto:davsan82@gmail.com">davsan82@gmail.com</a>.</p><p>Los datos legales del operador son temporales y serán completados antes del lanzamiento comercial.</p></ContentCard>
  </InstitutionalLayout>;
}
